//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartinTest.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public string Employe_ID { get; set; }
        public string Salary_Type { get; set; }
        public decimal Salary_Amount { get; set; }
        public System.DateTime Salary_Payment_Date { get; set; }
        public string Salary_Payment_Method { get; set; }
        public string Salary_Notes { get; set; }
    }
}
