//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartinTest.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary_Table
    {
        public string EID { get; set; }
        public string Type { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentMethod { get; set; }
        public string Notes { get; set; }
    
        public virtual Employe_Table Employe_Table { get; set; }
    }
}
